// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZW7drmRVj_O6z6475if7wiylijMDmJI0',
    appId: '1:127367560425:web:13e9369e28ebd082f54478',
    messagingSenderId: '127367560425',
    projectId: 'assignment-app-a95e3',
    authDomain: 'assignment-app-a95e3.firebaseapp.com',
    storageBucket: 'assignment-app-a95e3.appspot.com',
    measurementId: 'G-5ESTEJRPNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrV32a50evHwEz5UTj98DAtdJm3o46eRg',
    appId: '1:127367560425:android:30bd2eee8fb09312f54478',
    messagingSenderId: '127367560425',
    projectId: 'assignment-app-a95e3',
    storageBucket: 'assignment-app-a95e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs29EHj4S4qQsTVxSWK8fdlatvXlKDV9g',
    appId: '1:127367560425:ios:80dcd8f43ab261e4f54478',
    messagingSenderId: '127367560425',
    projectId: 'assignment-app-a95e3',
    storageBucket: 'assignment-app-a95e3.appspot.com',
    iosClientId: '127367560425-o17n19irp3ok9uo86obhjb0qpoq7i71t.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignmentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs29EHj4S4qQsTVxSWK8fdlatvXlKDV9g',
    appId: '1:127367560425:ios:80dcd8f43ab261e4f54478',
    messagingSenderId: '127367560425',
    projectId: 'assignment-app-a95e3',
    storageBucket: 'assignment-app-a95e3.appspot.com',
    iosClientId: '127367560425-o17n19irp3ok9uo86obhjb0qpoq7i71t.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignmentApp',
  );
}
